### ISSUE TITLE
error on php8

### ISSUE THREAD

**Issue by adhirmndl** [ToX82/logHappens#5]
Fatal error: Uncaught Error: Class "IntlDateFormatter" not found in /home/ubuntu/Test_Project/test/logHappens/libs/utilities.php:16 Stack trace: #0 /home/ubuntu/Test_Project/test/logHappens/parsers/apache24.php(13): toDateTime() #1 /home/ubuntu/Test_Project/test/logHappens/logics/Parsers.php(91): include('...') #2 /home/ubuntu/Test_Project/test/logHappens/logics/Parsers.php(76): Logics\Parsers->count() #3 /home/ubuntu/Test_Project/test/logHappens/routers/router.php(10): Logics\Parsers->countAll() #4 /home/ubuntu/Test_Project/test/logHappens/webroot/index.php(9): include('...') #5 {main} thrown in /home/ubuntu/Test_Project/test/logHappens/libs/utilities.php on line 16

---
master clone, 
composer install success
get this error on php8

**Comment by ToX82** [comment]
Hi! LogHappens actually needs the php-intl extension indeed, but since it's used only once I'll see if we can do without.

**Comment by ToX82** [comment]
Can you try again? Don't forget to pull the last modifications and run `composer update` again

**Comment by adhirmndl** [comment]
it's working fine, Thank you :)
