### ISSUE TITLE
Issue getting up and running

### ISSUE THREAD

**Issue by chrisvanmeer** [ToX82/logHappens#6]
Hi,

1. I have the project downloaded through the zip file into a readable directory for Apache
2. Created a site which exposes the `webroot` dir as documentroot.
3. Copied the `config.default.json` to `config.json`.
4. I did the `composer install` as the page suggested.
5. but now I get a 404 Not Found error when I go to `http://<fqdn>`, it wants to load `http://<fqdn>/display/info`

Could you help me solve this?

```bash
# cat config.json
{
    "parsers": {
        "apache": {
            "icon": "logos:apache",
            "color": "#104B73",
            "title": "Apache error",
            "file": "/var/log/apache2/error.log",
            "parser": "apache24"
        }
    }
}
```

```bash
# cat logs.conf
<VirtualHost *:80>
  ServerName logs.fqdn
  DocumentRoot /var/www/html/logs/webroot
  <Directory /var/www/html/logs/webroot/>
    Options Indexes FollowSymLinks
    AllowOverride All
  </Directory>
</VirtualHost>
```

```bash
# apachectl -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-06-14T13:30:55
```

```bash
# php -v
PHP 8.1.8 (cli) (built: Jul 11 2022 08:29:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.8, Copyright (c), by Zend Technologies
```

**Comment by chrisvanmeer** [comment]
Fixed it by cloning the repo in stead of using the zip file on the website.

**Comment by ToX82** [comment]
Hello Chris,
I'm glad that you have solved this, where did you download the zip file
though? I'going to fix It if I can

Il mar 19 lug 2022, 19:25 Chris van Meer ***@***.***> ha
scritto:

**Comment by chrisvanmeer** [comment]
It was from the website <https://tox82.github.io/logHappens/> and has the link <https://github.com/ToX82/logHappens/archive/master.zip>.

Now I can view the `error.log`, but I have lots more error logs in my `/var/log/apache2` directory. When I add them to the `config.json`, I get the error

```
DataTables warning: table id=DataTables_Table_0 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1
```

And the page also shows

```
Warning: Trying to access array offset on value of type null in /var/www/logHappens/logics/Parsers.php on line 115

Warning: Trying to access array offset on value of type null in /var/www/logHappens/logics/Parsers.php on line 116

Warning: Trying to access array offset on value of type null in /var/www/logHappens/logics/Parsers.php on line 117

Warning: Trying to access array offset on value of type null in /var/www/logHappens/logics/Parsers.php on line 118
```

The extra log files have the same markup as the general `error.log`. Any idea?

**Comment by chrisvanmeer** [comment]
Lol also fixed that, it was a config error in the `config.json` file, apparently, a new element with a `.` in the name caused the error.

**Comment by ToX82** [comment]
Maybe I could add a new check that the config.json file is valid and that all of the specified files are reachable. Noted for the next version :)
