### ISSUE TITLE
Feature Request: Search by Timestamps/Dates

### ISSUE THREAD

**Issue by hoferit** [ToX82/logHappens#9]
I am an active user of your application and I find it very useful for my daily tasks. However, I noticed that the current search functionality only allows searching for log entries, but not for timestamps or dates.

Being able to search for specific timestamps or dates would greatly enhance the usability of the application, as it would allow users to quickly navigate to logs from a specific time period.

Could you please consider adding this feature in a future update? 

Thank you for your time and consideration!

**Comment by ToX82** [comment]
Hello @hoferit , that's a good idea indeed, I will look into it!

**Comment by ToX82** [comment]
I've made an update that should work with this kind of search. I couldn't test it with all of the parsers though, so if you still have some issues related to this task please let me know.

P.s. you can search both with the extended date format `venerdì 19 gennaio 2024, 8:48:19` or this format `2024-01-19 08:48:19`. Partial searches like `2024-01` works too.
